# Generated by Django 4.0.3 on 2022-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150, null=True)),
                ('mname', models.CharField(max_length=150, null=True)),
                ('sname', models.CharField(max_length=150, null=True)),
                ('voters_stub', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('mname', models.CharField(max_length=150)),
                ('sname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('rvote', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('pnum', models.CharField(max_length=150, null=True)),
                ('pres', models.CharField(max_length=150)),
                ('vpres', models.CharField(max_length=150)),
                ('political_party', models.CharField(max_length=150)),
            ],
        ),
    ]
