# Generated by Django 4.0.3 on 2022-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dzellalsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='numvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cavite', models.CharField(max_length=150)),
                ('batangas', models.CharField(max_length=150)),
                ('laguna', models.CharField(max_length=150)),
                ('rizal', models.CharField(max_length=150)),
                ('qprov', models.CharField(max_length=150)),
            ],
        ),
    ]
